import React from 'react'
import Head from "next/head";
import Image from 'next/image'
import { BsGithub, BsArrowUpRightSquare } from "react-icons/bs"
import Link from "next/link"
import SlideUp from "./SlideUp"
import Navbar from './Navbar'
import { ThemeProvider } from 'next-themes'
import {motion as m} from "framer-motion"

const project=[
  {
    name:"CoinView",
    description:"Coinview is a cryptocurrency tracker app that has been developed using ReactJS and Material UI 5. This app allows users to keep track of their favorite cryptocurrencies and monitor their prices in real-time.",
    github:"https://github.com/KrishnaDhalla/CoinView.git",
    link:"https://coinview.netlify.app/",
    image:"/coinview2.webp"
  },
  {
    name:"Authentication",
    description:"The website showcases secure user authentication using Node.js, Express, MongoDB, JWT, and cookies.",
    github:"https://github.com/KrishnaDhalla/Authentication-using-Node.js",
    link:"https://authentication-using-nodejs.vercel.app/",
    image:"/auth.jpeg"
  },
  {
    name:"SpaceX Redesign",
    description:"Created a completely revamped SpaceX Website using Html Css and JavaScript with a superb UI experience and animations.",
    github:"https://github.com/KrishnaDhalla/SpaceX-Redesign",
    link:"https://spacexbykd.netlify.app/",
    image:"/spacex.jpeg"
  },
  {
    name:"Sobest",
    description:"Developed a responsive product showcasing website for Andri Agro Foods pvt.",
    github:"",
    link:"http://sobest.in/",
    image:"/sobest.jpeg"
  },
  
]
const Projects = () => {
  return (
    <m.div initial={{opacity:0}} animate={{opacity:1}} transition={{duration:0.3, ease:"easeInOut"}} exit={{opacity:0}}>
      <Head>
      <title>Projects | Krishna Dhalla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
   
    <section id="projects" className='bg-white px-10 md:px-20 lg:px-36 dark:bg-gray-900 md:pb-20 pb-10 min-h-screen'>
     <ThemeProvider enableSystem={true} attribute="class">
      <Navbar/>

      <h1 className="my-10 text-center font-bold text-4xl">
        Projects
        <hr className="w-6 h-1 mx-auto my-4 bg-teal-500 border-0 rounded"></hr>
      </h1>

      <div className="flex flex-col space-y-28">
        {project.map((project, idx) => {
          return (
            <div key={idx}>
              <SlideUp offset="-300px 0px -300px 0px">
                <div className="flex flex-col  animate-slideUpCubiBezier animation-delay-2 md:flex-row md:space-x-12 md:items-center">
                  <div className=" md:w-1/2">
                    <Link href={project.link}>
                      <Image
                        src={project.image}
                        alt=""
                        width={1000}
                        height={1000}
                        className="rounded-xl shadow-xl hover:opacity-70 "
                      />
                    </Link>
                  </div>
                  <div className="mt-8 md:mt-0 lg:mt-0 md:w-1/2">
                    <h1 className="text-3xl font-bold mb-6">{project.name}</h1>
                    <p className="text-xl leading-7 mb-4 text-neutral-600 dark:text-neutral-400">
                      {project.description}
                    </p>
                    <div className="flex flex-row align-bottom space-x-4">
                      <Link href={project.github} target="_blank">
                        <BsGithub
                          size={30}
                          className="hover:-translate-y-1 transition-transform cursor-pointer"
                        />
                      </Link>
                      <Link href={project.link} target="_blank">
                        <BsArrowUpRightSquare
                          size={30}
                          className="hover:-translate-y-1 transition-transform cursor-pointer"
                        />
                      </Link>
                    </div>
                  </div>
                </div>
              </SlideUp>
            </div>
          )
        })}
        
      </div>
    </ThemeProvider>
    </section>
    </m.div>
  )
}

export default Projects